# -*- coding: utf-8 -*-
"""HIERARICHAL_CLUSTERING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QuL5moYLZsRcJPlz9VXQbWZfQjHkxez
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/Mall_Customers.csv')

df

df.isnull().sum()

df.head()

df.tail()

df.describe()

df.info()

from sklearn.preprocessing import LabelEncoder

df_clust = df.copy()
le = LabelEncoder()
df_clust['Genre'] = le.fit_transform(df_clust['Genre'])

X = df_clust.iloc[:, 1:].values

import scipy.cluster.hierarchy as sch
dendrogram=sch.dendrogram(sch.linkage(X,method="ward"))

from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import LabelEncoder
df_clust = df.copy()
le = LabelEncoder()
df_clust['Genre'] = le.fit_transform(df_clust['Genre'])
X = df_clust.iloc[:, 1:].values
hc = AgglomerativeClustering(n_clusters=5, linkage='ward')
y_hc = hc.fit_predict(X)
df_clust['Cluster'] = y_hc

cluster_summary = df_clust.groupby('Cluster').mean()
print("Cluster Characteristics (Mean Values):")
print(cluster_summary)

